### ISSUE TITLE
Tạo header footer navbar dùng chung cho tất cả file

### ISSUE THREAD

**Issue by hien-huynh** [ITHub-NTU/ITHub#1]
Tạo file header, footer và navbar để các trang khác include vào. Sử dụng bootstrap và fontawesome.
Header gồm logo ITHUB, thanh tìm kiếm, nút đăng nhập ( avt người dùng, thông báo, tin nhắn nếu người dùng đăng nhập thành công)
Navbar gồm trang chủ, tài liệu, diễn đàn, bài tập cá nhân, liên hệ. 
Footer gồm thông tin đơn giản của ITHub

**Comment by phhamin** [comment]
yess we will have a common file for header, footer and navbar

**Comment by KietBee** [comment]
Mình đồng ý việc tạo layout dùng chung, nó sẽ tiết kiệm thời gian tạo các trang có giao diện giống nhau.
